### PR TITLE
[MIG] product_prices_update: Migration to 15.0

### PR DESCRIPTION
**Pull request by pablohmontenegro**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/442).

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
