### PR TITLE
[IMP] product_ux: dispatch report in format 10x15

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/516).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#520

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#520

**Pull request closed without merging**
