### PR TITLE
[MIG] product_catalog_aeroo_report_public_categ: Migration to 17.0

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/591).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc rebase -ff

**Comment by jcadhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc unable to stage: commits with multiple parents (f21b5f535dfa39f098988cf9be66ffd01d80c398) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
