### PR TITLE
[FIX] product_management_group: Allow superuser to skip that restriction on products

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/409).

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by nicomacr** [comment]
roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by nicomacr** [comment]
roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
