### PR TITLE
[FW][FIX] _cost_mrp: bom when variant is inactive

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#607

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/611).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by mav-adhoc** [comment]
@jcadhoc Fijate si esta bien y le hago review! Por lo pronto habría que hacer un rebase

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
