### PR TITLE
[FIX] product_ux: change of repository

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/536).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@vib-adhoc @maq-adhoc linked pull request(s) ingadhoc/stock#390 not ready. Linked PRs are not staged until all of them are ready.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: this PR is already reviewed, reviewing it again is useless.

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#539

**Pull request closed without merging**
