### PR TITLE
[FW][REF] product_catalog_aeroo_report: column adjustment

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#590
Forward-Port-Of: ingadhoc/product#584

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/608).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
