### PR TITLE
[FW][IMP] rep_cost: addlast cost update on tree view

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#414

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/415).

**Comment by fw-bot-adhoc** [comment]
Ping @jjscarafia cherrypicking of pull request ingadhoc/product#414 failed.

stdout:
```
Auto-merging product_replenishment_cost/__manifest__.py
CONFLICT (content): Merge conflict in product_replenishment_cost/__manifest__.py

```

stderr:
```
19:13:00.554770 git.c:439               trace: built-in: git cherry-pick 865bbeb2755a3a17e1e917c2859a11eedc5dbb8f
error: could not apply 865bbeb2... [IMP] rep_cost: addlast cost update on tree view
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+ override=ci/oba_without_tests

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

@nicomacr puede ser que no esté funcionando fw bot r+ ?

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@jjscarafia cuando el FW se edita para arreglar conflictos se mezcla con roboadhoc

**Pull request closed without merging**
