### PR TITLE
[FW][ADD] Product_ux: add zpl and pdf dispatch report

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#525

### CODE REVIEW

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/528).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jcadhoc** [comment]
Cerramos porque esto quedó viejo de cuando lo hicimos en product_ux, luego lo pasamos a stock_ux y ya esta correctamente en v16

**Pull request closed without merging**
