### PR TITLE
[FW][FIX] product_price_taxes_included: recursion check in price list

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#599

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/602).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @augusto-weiss cherrypicking of pull request ingadhoc/product#599 failed.

stdout:
```
Auto-merging product_price_taxes_included/models/product_pricelist.py
CONFLICT (content): Merge conflict in product_price_taxes_included/models/product_pricelist.py

```

stderr:
```
14:35:59.582755 git.c:444               trace: built-in: git cherry-pick 943ab7de95ea320fd88f028c6da0af1e13a6d0db
error: could not apply 943ab7de... [FIX] product_price_taxes_included: recursion check in price list
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by lef-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
