### PR TITLE
[FW][FIX] product_replenishment_cost: use round to calculated the value in different currency.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#423

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/424).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @jjscarafia cherrypicking of pull request ingadhoc/product#423 failed.

stdout:
```
Auto-merging product_replenishment_cost/models/product_template.py
CONFLICT (content): Merge conflict in product_replenishment_cost/models/product_template.py

```

stderr:
```
17:36:44.841307 git.c:439               trace: built-in: git cherry-pick 6a07e472790d2c81192163f63cd81a0de0a73f49
error: could not apply 6a07e472... [FIX] product_replenishment_cost: use round to calculated the value in different currency.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by jjscarafia** [comment]
@nicomacr resolves el conflicto please?

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
