### PR TITLE
[17.0][MIG] product_replenishment_cost_stock: Migration to 17.0

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/634).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc rebase--ff

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Pull request closed without merging**
