### PR TITLE
[FW][FIX] Added api.depends_context to force the commpany

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Es a 13 el cambio, me confundí y le puse 15 al nombre del branch

Forward-Port-Of: ingadhoc/product#452

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/453).

**Comment by fw-bot-adhoc** [comment]
Ping @JoelZilli, @nicomacr
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @JoelZilli, @nicomacr

ci/oba_without_tests failed on this forward-port PR

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
