### PR TITLE
[MIG] product_replenishment_cost_mrp: Migration to 16.0

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/483).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/483).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
