### PR TITLE
[FIX] product_ux: fix in price list search

### PR DESCRIPTION
**Pull request by lef-adhoc**
NOTA volvemos a poner = en vez de ilike para mantener que sea como en v13 y ademas mantenerlo alineado a oca product pack https://github.com/OCA/product-pack/blob/36937ac56dda430622c4c910676ebc50e0ae8bcf/product_pack/models/product_product.py#L55

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/578).

**Comment by jjscarafia** [comment]
@roboadhoc r+ mezclamos igual porque el error es de IAP

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
