### PR TITLE
[MIG] product_catalog_aeroo_report: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/447).

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Pull request closed without merging**
