### PR TITLE
[MIG] product_ux: Migration to 18.0

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/671).

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @ced-adhoc. I'm afraid I can't do that.

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
