### PR TITLE
[FIX] product_Expiry_ux: manifest version

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/548).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#567

**Pull request closed without merging**
