### PR TITLE
[13.0] [FIX] product_catalog_aeroo_report: Use the whole_pack_price now for the whole pack price.

### PR DESCRIPTION
**Pull request by nicomacr**
After this [PR](https://github.com/OCA/product-pack/pull/46) was merged we use this new flag

### CODE REVIEW

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/405).

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You can't review+.

**Review by PabloPaezSheridan — APPROVED** [review]

**Pull request merged**
