### PR TITLE
[ADD] Product_ux: add zpl and pdf dispatch report

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/525).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#528

**Pull request closed without merging**
