### PR TITLE
[IMP]price_security_replenishment_cost: new module

### PR DESCRIPTION
**Pull request by jok-adhoc**
hides replenishment cost's fields using price_security's groups

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/535).

**Comment by matiasperalta1** [comment]
@roboadhoc rebase-ff

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#547

**Pull request closed without merging**
