### PR TITLE
[FW][IMP] price_security: Make optional hide product_can_modify_prices field

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#704

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/705).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @feg-adhoc cherrypicking of pull request ingadhoc/product#704 failed.

stdout:
```
Auto-merging price_security/views/account_move_views.xml
CONFLICT (content): Merge conflict in price_security/views/account_move_views.xml
Auto-merging price_security/__manifest__.py
CONFLICT (content): Merge conflict in price_security/__manifest__.py

```

stderr:
```
14:19:04.077101 git.c:444               trace: built-in: git cherry-pick c06aa4b394b6a71538c84bfdd70058181c699ac0
error: could not apply c06aa4b3... [IMP] price_security: Make optional hide product_can_modify_prices field
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
