### PR TITLE
[MIG] product_pricelist: Migration to 17.0

### PR DESCRIPTION
**Pull request by mem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/561).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jcadhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
