### PR TITLE
[MIG] product_management_group: Migration to 18.0

### PR DESCRIPTION
**Pull request by joa-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/686).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc +

**Pull request closed without merging**
