### PR TITLE
[15.0] [FIX] product_catalog_aeroo_report: Use the whole_pack_price now for the whole pack price.

### PR DESCRIPTION
**Pull request by nicomacr**
…

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/406).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by nicomacr** [comment]
@roboadhoc check

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You can't check.

**Comment by roboadhoc** [comment]
No update to pr head

**Comment by nicomacr** [comment]
roboadhoc r+

**Pull request merged**
