### PR TITLE
[FW][REF] product_catalog_aeroo_report: column adjustment

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#584

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/589).

**Comment by fw-bot-adhoc** [comment]
This PR targets 15.0 and is part of the forward-port chain. Further PRs will be created up to 17.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc the next pull request (ingadhoc/product#590) is in conflict. You can merge the chain up to here by saying
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by lav-adhoc** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
