### PR TITLE
[MIG] product_template_tree_first: Migration to 16.0

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/477).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@matiasperalta1 you may want to rebuild or fix this PR as it has failed CI.

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
