### PR TITLE
[MIG] product_planned_price: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/418).

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Review by PabloPaezSheridan — APPROVED** [review]

**Comment by PabloPaezSheridan** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@PabloPaezSheridan, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
