### PR TITLE
[REF] product_catalog_aeroo_report: column adjustment

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/584).

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#590

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#608

**Pull request closed without merging**
