### PR TITLE
[FIX] product_pricelist: add sudo in compute price method

### PR DESCRIPTION
**Pull request by lef-adhoc**
This is done because if there is a record rule in the pricelist that cannot be edited (for example there is one in the price_security module) this avoids that record rule, there is no problem because it is only to see the price.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/712).

**Comment by cem-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @cem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#713

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @cem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#713

**Pull request closed without merging**
