### PR TITLE
[FIX] product_catalog_aeroo_report: the price already comes with tax …

### PR DESCRIPTION
**Pull request by lef-adhoc**
…included

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/604).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#605

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#605

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#605

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#605

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#605

**Pull request closed without merging**
