### PR TITLE
[MIG] product_internal_code: Migration to 16.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/493).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
