### PR TITLE
[FIX] product_management_group: Allow superuser to skip that restriction on products

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/407).

**Review by jjscarafia — APPROVED** [review]

**Comment by nicomacr** [comment]
robadhoc +

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
roboadhoc retry

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. Retry makes no sense when the PR is not in error.

**Comment by nicomacr** [comment]
roboadhoc rebase-merge

**Comment by roboadhoc** [comment]
Merge method set to rebase and merge, using the PR as merge commit message

**Pull request merged**
