### PR TITLE
[IMP] product_replenishment_cost: replenishment_cost_last_update adju…

### PR DESCRIPTION
**Pull request by vib-adhoc**
…stment

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/460).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/460).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Pull request closed without merging**
