### PR TITLE
[FIX] product_uoms_purchase: target correct field in inherited view

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/643).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#644

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#644

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#644

**Comment by fw-bot-adhoc** [comment]
@ALopez-Adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#644

**Pull request closed without merging**
