### PR TITLE
[FIX] price_security: migration bug

### PR DESCRIPTION
**Pull request by zaoral**
ticket 55180
---
type field does not exist anymore, use move_type instead

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/457).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc  override=ci/oba_without_tests p=0

**Pull request closed without merging**
