### PR TITLE
[MIG] product_currency: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/411).

**Comment by georginacicerchia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@georginacicerchia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
