### PR TITLE
[MIG] product_uoms, product_uoms_sale, product_uoms_purchase: Migration to 16.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/479).

**Review by maq-adhoc — DISMISSED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc  r+

**Comment by JoelZilli** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @JoelZilli: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@vib-adhoc @maq-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by JoelZilli** [comment]
@roboadhoc rebase-merge r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and merge, using the PR as merge commit message.

**Comment by roboadhoc** [comment]
I'm sorry, @JoelZilli: this PR is already reviewed, reviewing it again is useless.

**Comment by JoelZilli** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
