### PR TITLE
[ADD] product_expiry_ux: create module.

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/product/pull/467).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/467).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#504

**Pull request closed without merging**
