### PR TITLE
[FW][ADD] product_expiry_ux: expiration_date in lot

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#609

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/612).

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc cherrypicking of pull request ingadhoc/product#609 failed.

stdout:
```
Auto-merging product_expiry_ux/__manifest__.py
CONFLICT (content): Merge conflict in product_expiry_ux/__manifest__.py

```

stderr:
```
13:32:39.761282 git.c:444               trace: built-in: git cherry-pick 0f05cdbea966f164c315074f526e62ae371f96e0
error: could not apply 0f05cdbe... [ADD] product_expiry_ux: expiration_date in lot
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc linked pull request(s) ingadhoc/stock#471 not ready. Linked PRs are not staged until all of them are ready.

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
