### PR TITLE
[FIX] Product_ux: Clean spaces and change barcode

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/521).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#522

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#522

**Pull request closed without merging**
