### PR TITLE
[FW][IMP] product_replenishment_cost: replenishment_cost_last_update adju…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…stment

Forward-Port-Of: ingadhoc/product#460

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/492).

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @augusto-weiss cherrypicking of pull request ingadhoc/product#460 failed.

stdout:
```
Auto-merging product_replenishment_cost/__manifest__.py
CONFLICT (content): Merge conflict in product_replenishment_cost/__manifest__.py

```

stderr:
```
14:32:38.636836 git.c:444               trace: built-in: git cherry-pick 9fc2535fa8e3a5bf9c7344bd99dc074d82afdfa5
error: could not apply 9fc2535f... [IMP] product_replenishment_cost: replenishment_cost_last_update adjustment
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@vib-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc  override=ci/runbot-oba

**Pull request closed without merging**
