### PR TITLE
[IMP] product_planned_price: batch cron runs

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/551).

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
