### PR TITLE
[FIX] catalog_report: prices can include taxes

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/537).

**Comment by JrAdhoc** [comment]
@roboadhoc  override=ci/runbot-oba r+

**Comment by roboadhoc** [comment]
@JrAdhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @JrAdhoc: you are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
