### PR TITLE
[FW][FIX] product_pricelist: add sudo in compute price method

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
This is done because if there is a record rule in the pricelist that cannot be edited (for example there is one in the price_security module) this avoids that record rule, there is no problem because it is only to see the price.

Forward-Port-Of: ingadhoc/product#712

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/713).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @cem-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @cem-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @cem-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
