### PR TITLE
[FW][ADD] product_brand_report: new module for print brand in reports

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/product#566

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/568).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti ci/runbot-oba failed on this forward-port PR

**Comment by lef-adhoc** [comment]
@Bruno-Zanotti Para migrar este módulo a 17 habría que mezclar esto ?

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
