### PR TITLE
[FIX]product_catalog_aeroo_report: taxed_lst_price

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/532).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
