### PR TITLE
[ADD] product_brand_report: new module for print brand in reports

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/product/pull/566).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/product#568

**Pull request closed without merging**
